(function() {
  require('../test/cssjs-tests/test-jqlite');
  require('../test/cssjs-tests/test-util');
  require('../test/react-tests/test-appbar');
  require('../test/react-tests/test-button');
  require('../test/react-tests/test-caret');
  require('../test/react-tests/test-checkbox');
  require('../test/react-tests/test-col');
  require('../test/react-tests/test-container');
  require('../test/react-tests/test-divider');
  require('../test/react-tests/test-dropdown');
  require('../test/react-tests/test-form');
  require('../test/react-tests/test-panel');
  require('../test/react-tests/test-radio');
  require('../test/react-tests/test-row');
  require('../test/react-tests/test-select');
  require('../test/react-tests/test-tabs');
  require('../test/react-tests/test-text-input');
})();
